### ISSUE TITLE
Option to toogle view would have been great to locate folders.

### ISSUE THREAD

**Issue by PranavBhattarai** [zhanghai/MaterialFiles#361] opened 2020-08-18 11:32 UTC
I think it's pretty common to provide an option by clicking which user can toogle how they want to view their files. This is seen in desktop file manager, and also in mobile file manager. 
![USER_SCOPED_TEMP_DATA_orca-image--883207157](https://user-images.githubusercontent.com/32763112/90507804-3b917380-e176-11ea-8a60-66022dac3e4c.jpeg)

![USER_SCOPED_TEMP_DATA_orca-image--1012360046](https://user-images.githubusercontent.com/32763112/90507861-52d06100-e176-11ea-844a-b6f45ea1ec38.jpeg)

**Comment by zhanghai** [comment] 2020-09-02 06:53
Duplicate of #152, and yes I think this is a good idea, just I need more time and effort.

**Closed by zhanghai** 2020-09-02 06:53 UTC
