### ISSUE TITLE
[Feature Request] Add "Save on device"

### ISSUE THREAD

**Issue by Ojd2000** [zhanghai/MaterialFiles#626] opened 2021-11-21 17:03 UTC
Add intent action to enable a "Save on device" option in Android Share menu.
Sometimes it happens that I'd like to save some document or photo to my device, but if I try to "share" it, I get no option to do so. Previous file managers I used had this feature. Now I need to share them with a self chat in some messenger app and download it from there.

**Comment by PhillyMay** [comment] 2022-07-02 06:35
I would also like to see this feature. Material files is awesome, because i have direct access to my personal nas. Currently I have to "share" a file to the standard file exlorer on my phone, save it on the download folder, switch to the material files App, go to the download folder, cut the file and paste it on the desired location. With direct access to material files via the share sheet it would be much simpler

**Comment by NA0341** [comment] 2023-02-27 13:08
Please also make sure when implementing this feature that you cover the different cases: It would be extremely helpful to share text and save it to a file.

Also, in [Simple File Manager Pro from SimpleMobileTools](https://github.com/SimpleMobileTools/Simple-File-Manager), this feature is already implemented **but** gives an error on almost any occasion.

It might be a good idea to invest a little more effort to make a pipeline - like processing which ensures that it can successfully save as many formats as possible.

1. Analyze content type & detect if it is raw or a file (encapsulated into a container)
2. If content type = raw -> Create dialogue (filetype & name chooser)
3. Further processing steps…

**Comment by ChaosNicro** [comment] 2023-12-09 11:45
I would also want to second this.

PS: to make cleanup easier here are all the open copies I found (maybe pin one as the "master", so people are less likely to create more):
#976 
#913 
#870 
#483 
#305

**Comment by javaman97** [comment] 2024-04-09 05:48
@Ojd2000 I would like to work on this feature, would you please assign it to me?

**Comment by zhanghai** [comment] 2024-04-09 06:04
@javaman97 Please check out https://github.com/zhanghai/MaterialFiles/blob/master/.github/pull_request_template.md - but of course you are free to maintain your own (GPLv3) fork.

**Comment by zhanghai** [comment] 2024-04-09 06:06
Duplicate of #483.

**Closed by zhanghai** 2024-04-09 06:06 UTC
