### ISSUE TITLE
[Improvement] Add the option to display file sizes in binary units

### ISSUE THREAD

**Issue by theFireProjet** [zhanghai/MaterialFiles#311] opened 2020-06-20 00:02 UTC
### Overview
Currently, in Material Files, file sizes are displayed in decimal units.
<details><summary>Decimal units</summary>
In decimal units, a file of 4,718,592 bytes is displayed as 4.72 MB. This is because M (mega) stands for 1,000,000 (one million).<br>
<ul><b>4,718,592 B</b> ≈ 4.72 B * 1,000 * 1,000 = 4.72 B * 1,000,000 = <b>4.72 MB</b></ul></details>

However, most operating systems, programs, apps and web pages use binary units for file sizes. 
<details><summary>Binary units</summary>
In binary units, a file of 4,718,592 byte is displayed as 4.50 MiB.<br>
This is the case because Mi (mebi, megabinary) stands for 1,048,576 = 1,024 * 1,024 = 2<sup>10</sup> * 2<sup>10</sup>.<br>
<ul><b>4,718,592 B</b> = 4.50 * 1,024 * 1,024 B = 4.50 * 1,048,576 B = <b>4.50 MiB</b></ul>
Although all software usually displays file sizes in binary units, they still use the better known unit symbol MB which is technically incorrect. So the correct notation for 4,718,... byte is 4.50 MiB but often it's called 4.50 MB.</details>

In result, it's hard to compare a file size from Material Files to other sources.

### Feature request
Add an option to the settings to choose how to display file sizes, in decimal (KB, MB, GB) or binary units (KiB, MiB, GiB).
Binary units: see https://en.wikipedia.org/wiki/Mebibyte (f.e. table to the right).

### User benefit
All common platforms and software display file sizes in binary units. The fact that Material Files steps out of line is a disadvantage for the user because it makes file sizes uncomperable as they are displayed in a different unit without complicated calculations. The best solution is if the user can choose how to display file sizes. It should be possible to view the size of a file in Material Files in the common, well known format that is used in other software, too.

**Comment by zhanghai** [comment] 2020-06-20 00:20
> All common platforms and software display file sizes in binary units.

This is not true. GNOME Nautilus uses decimal units, and the Android system, [the most popular OS](https://en.wikipedia.org/wiki/Usage_share_of_operating_systems), uses decimal units (since years ago). This app uses the API provided by Android platform to format size info, so that it is consistent with other parta of the system (e.g. Settings).

**Comment by zhanghai** [comment] 2020-06-20 00:23
Duplicate of #284.

**Closed by zhanghai** 2020-06-20 00:23 UTC

**Comment by theFireProjet** [comment] 2020-06-20 00:50
> 
> 
> > All common platforms and software display file sizes in binary units.
> 
> This is not true. GNOME Nautilus uses decimal units, and the Android system, [the most popular OS](https://en.wikipedia.org/wiki/Usage_share_of_operating_systems), uses decimal units (since years ago). This app uses the API provided by Android platform to format size info, so that it is consistent with other parta of the system (e.g. Settings).

Hi, thanks for the reply.

I realize saying "all" was exaggerated. But I'm of the opinion that the most used platforms, software and web pages display file sizes in binary units.
You say, Android system is the most "popular" (most used?) platform and uses decimal units. But the point is, people don't see what's inside Android system. So the question that matters is, what do people actually see?
- UNIX and Linux are niche products mostly for advanced users and servers.
- Windows is used by most people and most of them only ever use Windows Explorer as a file manager that displays binary units.
- And on Android, people don't see what's inside the system. People see things through their manufactorer's UI and a whole variety of apps. <details><summary>Examples</summary>
F.e. the stock Android file manager uses decimal units, however the stock file manager on Samsung's UI uses binary units and the stock Android file manager is hidden. It doesn't even appear on the apps screen.
The Android settings (f.e. the Apps list) use decimal units, however the parts of the settings that were redesigned by Samsung (f.e. "Device maintanance") use binary units.
Browsers like Chrome and Firefox use binary units.
Apps and web pages like Google Play use binary units.</details>

On #284 you said, file sizes should be consistent. But consistent with what numbers? The numbers nobody sees? Or with the numbers most people actually see? Why not let the user choose which numbers they want to be consistent with?
You mentioned the additional effort to localize. Do you mean translating? What needs to be translated? Units are international, no need to translate.
