### ISSUE TITLE
Share to MaterialFiles for Save as

### ISSUE THREAD

**Issue by Ged296123** [zhanghai/MaterialFiles#483] opened 2021-03-30 10:34 UTC
Ability to share any file to MaterialFiles (Save As) would be great. This would help transferring files between profiles (i.e. work and personal) with no need for root access.

Thanks for the great app and your dedication.

**Comment by zhanghai** [comment] 2021-03-30 11:24
Note to myself: This could be very similar to #153.

**Comment by Civilian-No-001** [comment] 2021-05-02 04:27
@zhanghai  wow, very much looking forward to this new feature of 1.3.0.

Would you consider modifying the name to distinguish it from the built-in "files" in the system? Like "MD files". Or this application can safely replace "files"?

**Comment by PYUDNG** [comment] 2024-04-15 01:27
> Just came across a simple app that does this job. Wanted to share just in case it comes handy.
> 
> https://github.com/lmj0011/save-on-device

Thx, but still looking forward for this feature in MaterialFiles because I love its beautiful and easy-to-use interface.
Also, this issue has been opened for about 3 yrs, can I still expect this feature being implemented in a future update or this issue will be simply ignored (as [`wont fix`](https://github.com/zhanghai/MaterialFiles/labels/wontfix))?

**Comment by zhanghai** [comment] 2024-04-15 07:05
> can I still expect this feature being implemented in a future update or this issue will be simply ignored (as [`wont fix`](https://github.com/zhanghai/MaterialFiles/labels/wontfix))?

Well, I never marked this as wont fix so it's still on my list.

You can also see that this is actually on a release milestone, which is one active indication of my intention to implement it - unlike other niche/hard-to-implement requests that I can't say it's unimportant for the reporter but I can't say it's important/feasible for me either. (Oh, but please never ask me to add a feature to a milestone, I don't want the doubled awkwardness to decline/ignore that.)

I hope people can understand I have my life/work/health issues to deal with, so what's needed here is time. Same thing happened for Grid View and WebDAV and they were added in 1.6.0 and 1.7.0.

**Comment by PYUDNG** [comment] 2024-04-15 12:38
Thanks for your patient reply and I'm happy to hear that this feature is still in your list (and on a release milestone). Besides I'm sorry for what I've ignored previously, the release milestone (I never noticed that there was a feature called _release milestone_ in Github before, OMG!). I'm sorry for wasting your time, and grateful for your hard work in developing and maintaining this project, and answering silly questions like mine with patience. Wish you all the best in your own life❤.

**Closed** 2024-04-16 02:00 UTC
Labels: enhancement

**Comment by PYUDNG** [comment] 2024-04-26 11:31
Thanks for your implementation of this feature.

This is a bug report with the new save-as functionality in [android work profile](https://developer.android.com/work/managed-profiles).

The "save as" functionality seems unable to handle files that are shared _from **other app in mainland**, to **android work profile**_. When I'm trying to do that, I got this error:
<details>
<summary>screenshot: error message popup</summary>
<img src="https://github.com/zhanghai/MaterialFiles/assets/63054558/7f5c0cec-83f0-421d-8244-71b0112ac9c9" alt="screenshot of error message" title="Screenshot_20240426_185438_me zhanghai android files">
</details>

To make it clear ,here's steps to reproduce this error on my device:
- First, I've installed MaterialFiles both in mainland and my work profile, and [aves](https://developer.android.com/work/managed-profiles) installed in mainland
- share a picture file from aves, to work profile
- use work profile's MaterialFiles' save-as functionality
- error message pop-up

It doesn't matter where to save the file, as you may noticed in the screenshot above, I chose to save that picture in my work profile's Download directory, which is a public directory, but this error still comes out.
Besides, Sharing files between two areas from MaterialFiles to MaterialFiles would success with no error occurred. Only sharing from **another app** in mainland to **MaterialFiles** in work profile fails.

PS: 
- I'm using [Island](https://github.com/oasisfeng/island) to create and manage my android work profile.
- <details><summary>image: my android version</summary><img src="https://github.com/rRemix/APlayer/assets/63054558/87ce6116-13d4-4b49-a0e0-60ac8967f9d7"></details>

**Comment by zhanghai** [comment] 2024-05-23 09:40
I tried to reproduce this on OxygenOS Android 14 with Island and Aves/Google Photos/DocumentsUI and they all worked fine with saving to work profile.

**Comment by PYUDNG** [comment] 2024-05-28 16:20
Thanks for your testing and reply. I'm using HarmonyOS on a HUAWEI device, which may be the reason for this issue. Currently I'm using the save-as functionality combined with the save-on-device app you mentioned above, and no error occurs. Thank you for your hard work again❤️️.
