### ISSUE TITLE
materialfiles in combination with keepassdx

### ISSUE THREAD

**Issue by Joppla** [zhanghai/MaterialFiles#727] opened 2022-03-26 12:28 UTC
See also: https://github.com/Kunzisoft/KeePassDX/issues/1280

Since last weeks MaterialFiles crashes. 

It happens when my browser try to open KeePassDx to get username and password. The database file for KeePassDx is in the cloud and it use MaterialFiles to connect to it.

When I open KeePassDX MaterialFiles crash also.

Only when I first open MaterialFiles and than KeePassDX everything works fine.

I don't know if the problem is in MaterialFiles or in KeePassDX but it is anoying.

Hopefully can somebody find the solution.

PS my Samsung G S9 works with android 10.

**Comment by zhanghai** [comment] 2022-03-26 22:59
Duplicate of #716.

**Closed by zhanghai** 2022-03-26 22:59 UTC
