### ISSUE TITLE
Using 3 dot menu Share on SMB file crashes app (NetworkOnMainThreadException)

### ISSUE THREAD

**Issue by bubbleguuum** [zhanghai/MaterialFiles#651] opened 2022-01-03 21:45 UTC
Android version: 12
Device: Pixel 4a
App version 1.3.1

I created a SMB share.

triggering '3 dot menu > Share' on a SMB file results in a `NetworkOnMainThreadException`, hard crashing the app:

```
android.os.NetworkOnMainThreadException
                         E      at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1668)
                         E      at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
                         E      at java.net.SocketOutputStream.write(SocketOutputStream.java:161)
                         E      at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
                         E      at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
                         E      at c8.b.c(:10)
                         E      at v7.a.M0(:23)
                         E      at z7.b.j(:6)
                         E      at a8.h.j(:2)
                         E      at a8.h.p(Unknown Source:0)
                         E      at a8.c.q(:1)
                         E      at a8.c.u(:1)
                         E      at md.c.h(:13)
                         E      at ld.c.w(:1)
                         E      at rb.c0.o0(:2)
                         E      at rb.c0.G0(Unknown Source:14)
                         E      at me.zhanghai.android.files.file.FileProvider.query(Unknown Source:54)
                         E      at android.content.ContentProvider.query(ContentProvider.java:1408)
                         E      at android.content.ContentProvider.query(ContentProvider.java:1504)
                         E      at android.content.ContentProvider$Transport.query(ContentProvider.java:272)
                         E      at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
                         E      at android.os.Binder.execTransactInternal(Binder.java:1179)
                         E      at android.os.Binder.execTransact(Binder.java:1143)
             System.err  W  java.util.concurrent.ExecutionException: com.hierynomus.smbj.common.SMBRuntimeException: java.lang.InterruptedException
                         W      at k7.d.get(:2)
                         W      at k7.b.get(Unknown Source:2)
                         W      at ld.f$a.run(Unknown Source:2)
                         W  Caused by: com.hierynomus.smbj.common.SMBRuntimeException: java.lang.InterruptedException
                         W      at com.hierynomus.smbj.common.SMBRuntimeException$a.a(:1)
                         W      at x2.h.b(Unknown Source:123)
                         W      at k7.d.get(:1)
                         W      ... 2 more
                         W  Caused by: java.lang.InterruptedException
                         W      at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2042)
                         W      at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2076)
                         W      at x2.h.b(Unknown Source:59)
                         W      ... 3 more

```

**Comment by zhanghai** [comment] 2022-02-07 07:34
This is a duplicate of #656 and has been fixed. The fix will be released in the next app version.

**Closed by zhanghai** 2022-02-07 07:34 UTC
Labels: bug, duplicate
