### ISSUE TITLE
Search file types, not directories

### ISSUE THREAD

**Issue by GokdenizK** [zhanghai/MaterialFiles#509] opened 2021-05-03 10:44 UTC
Hello, would you consider adding an option to make the app search for file extensions like .mp4, .docx etc. when pressed on one of the categories in the sub menu, because not every phone has directories like movies and documents. Also, I want to see my documents and music files etc. when they are also in other folders, so I would really appreciate if you added this as an option.

**Comment by zhanghai** [comment] 2021-05-07 03:10
Duplicate of #443.

**Closed by zhanghai** 2021-05-07 03:10 UTC
