### ISSUE TITLE
Add ZIP & 7Z Support

### ISSUE THREAD

**Issue by trymeouteh** [zhanghai/MaterialFiles#268] opened 2020-04-28 05:31 UTC
Please allow suppprt for opening, adding files to, removing files from and creating ZIP and 7Z files. Including setting the compression strength on these files and encryption. There is no good app on FDroid that allow yout to work with ZIP and 7Z files.

**Comment by zhanghai** [comment] 2020-04-28 07:17
Duplicate of #193.

The app already works with simple ZIP and 7Z archives, and you can create them as well. It won't be easy to implement advanced use cases and I don't have a plan for it in the near future - please use a dedicated archiver app instead.

**Closed by zhanghai** 2020-04-28 07:17 UTC

**Comment by trymeouteh** [comment] 2020-04-28 17:13
Does anyone know of any advanced ZIP and 7Z apps on FDroid?

**Comment by EchedeyLR** [comment] 2020-11-29 12:44
FLOSS? The last FLOSS archiver for Android (and the only one) was abandoned and its source code dissapeared. You can find references to its existence if you check alternatives for WinRAR or ZArchiver for Android in https://alternativeto.net
