### ISSUE TITLE
Support for new Storages/Cloud storage

### ISSUE THREAD

**Issue by Feuerswut** [zhanghai/MaterialFiles#619] opened 2021-11-04 08:43 UTC
This is about the upper left hand corner in the burger menu.

I cannot add cloud storage because:
1. The default Android storage browser doesnt let me access Google Drive or OneDrive
2. Direct connection to cloud services are not supported
3. I cannot edit in the Path value box the storage options, I always have to choose the path using the default Android file browser.
I could just type: content://com.google.android.apps.docs.storage/PATH
for Google Drive if the App would allow it...

Please fix it! Otherwise great app!!
Device ---    Pixel 6/Android 12

**Comment by zhanghai** [comment] 2021-11-04 19:39
1. Yes.
2. Duplicate of #95.
3. It won't work, Material Files won't have access to that URI.

**Closed by zhanghai** 2021-11-04 19:39 UTC

**Comment by Feuerswut** [comment] 2021-11-04 20:05
I just think about what KeePassDX is using. Because I can access Google Drive via the File Explorer there. Or is that just for singular documents?

**Comment by zhanghai** [comment] 2021-11-04 22:56
Yes, that only works for singlular documents.
