### ISSUE TITLE
Cannot open files through SFTP

### ISSUE THREAD

**Issue by QmZh** [zhanghai/MaterialFiles#1167] opened 2024-03-18 12:25 UTC
I'm using version 1.7.0 on F-droid, it cannot open files through SFTP. 
When I open an image file it shows
java.lang.NoSuchFieldError: No instance field $transform of type Lf4/ I; in class Lg5/e; or its superclasses (declaration of 'g5.e' appears in base.apk)
![Screenshot_2024-03-18_19-48-56_1](https://github.com/zhanghai/MaterialFiles/assets/26890029/622f470e-de9f-45d2-8acc-3bf954dce889)

Version 1.6.2 works. Another thing is that the SFTP, SMB or FTP speed are very low compared to another file manager. The other one is around 10~20 MB/s, it's around 100~500 KB/s.

**Comment by zhanghai** [comment] 2024-03-18 18:10
Duplicate of #1154

**Closed by zhanghai** 2024-03-18 18:10 UTC
