### ISSUE TITLE
Can't access /storage/emulated/` on Android 11

### ISSUE THREAD

**Issue by linsui** [zhanghai/MaterialFiles#516] opened 2021-05-28 04:48 UTC
I want to access work profile with root access. On Android 10 it works well but on Lineage 18.1 Android 11 I get `No such file or directory` and `Permission denied` error. Thanks!

I installed Material Files in work profile and it doesn't work. It can't access any file.

**Comment by zhanghai** [comment] 2021-05-30 07:06
Duplicate of #487.

**Closed by zhanghai** 2021-05-30 07:06 UTC
