### ISSUE TITLE
Crash when trying to open a zip file

### ISSUE THREAD

**Issue by pixincreate** [zhanghai/MaterialFiles#1042] opened 2023-10-15 15:38 UTC
Device: Bluejay
Android Version: 14
OS: GrapheneOS

```
type: crash
osVersion: google/bluejay/bluejay:14/UP1A.231005.007/2023101300:user/release-keys
package: me.zhanghai.android.files:34
process: me.zhanghai.android.files
processUptime: 0 + 0 ms

signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000008

backtrace:
      #00 pc 0000000000081230  /data/app/~~ODoT_UPrbigESYC_0yG6mw==/me.zhanghai.android.files-0HL06B6etuKLpAjc6spzWg==/lib/arm64/libarchive-jni.so (Java_me_zhanghai_android_libarchive_Archive_free+68) (BuildId: 5aac375a93b05300900d02c95f753f1f160904ba)
      #01 pc 0000000000969ed4  /data/app/~~ODoT_UPrbigESYC_0yG6mw==/me.zhanghai.android.files-0HL06B6etuKLpAjc6spzWg==/oat/arm64/base.odex (art_jni_trampoline+116)
      #02 pc 00000000012dd8e0  /data/app/~~ODoT_UPrbigESYC_0yG6mw==/me.zhanghai.android.files-0HL06B6etuKLpAjc6spzWg==/oat/arm64/base.odex (yl.k.o+1728)
      #03 pc 0000000000d382b0  /data/app/~~ODoT_UPrbigESYC_0yG6mw==/me.zhanghai.android.files-0HL06B6etuKLpAjc6spzWg==/oat/arm64/base.odex (bd.f.l+192)
      #04 pc 0000000000d3bf1c  /data/app/~~ODoT_UPrbigESYC_0yG6mw==/me.zhanghai.android.files-0HL06B6etuKLpAjc6spzWg==/oat/arm64/base.odex (bd.g.s+332)
      #05 pc 00000000016ac178  /data/app/~~ODoT_UPrbigESYC_0yG6mw==/me.zhanghai.android.files-0HL06B6etuKLpAjc6spzWg==/oat/arm64/base.odex (androidx.lifecycle.d1.j+536)
      #06 pc 0000000000e9b43c  /data/app/~~ODoT_UPrbigESYC_0yG6mw==/me.zhanghai.android.files-0HL06B6etuKLpAjc6spzWg==/oat/arm64/base.odex (h9.c.k+700)
      #07 pc 0000000000f7c3a4  /data/app/~~ODoT_UPrbigESYC_0yG6mw==/me.zhanghai.android.files-0HL06B6etuKLpAjc6spzWg==/oat/arm64/base.odex (me.zhanghai.android.files.provider.root.u.s+308)
      #08 pc 00000000008c710c  /data/app/~~ODoT_UPrbigESYC_0yG6mw==/me.zhanghai.android.files-0HL06B6etuKLpAjc6spzWg==/oat/arm64/base.odex (k5.l.call+1276)
      #09 pc 0000000000254a94  /system/framework/arm64/boot.oat (java.util.concurrent.FutureTask.run+180) (BuildId: 5b2c7eed028a9059e21581987ab20d77395c2735)
      #10 pc 00000000002b3d3c  /system/framework/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor.runWorker+796) (BuildId: 5b2c7eed028a9059e21581987ab20d77395c2735)
      #11 pc 00000000002b0e60  /system/framework/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor$Worker.run+64) (BuildId: 5b2c7eed028a9059e21581987ab20d77395c2735)
      #12 pc 000000000015f828  /system/framework/arm64/boot.oat (java.lang.Thread.run+72) (BuildId: 5b2c7eed028a9059e21581987ab20d77395c2735)
      #13 pc 00000000002109a4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: 461d63ef591fa8993cb520492483029d)
      #14 pc 0000000000253b4c  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+172) (BuildId: 461d63ef591fa8993cb520492483029d)
      #15 pc 000000000069ac78  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1416) (BuildId: 461d63ef591fa8993cb520492483029d)
      #16 pc 00000000000d093c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204) (BuildId: f33b0edef1abac7e4e17c501eeb62737)
      #17 pc 0000000000065570  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: f33b0edef1abac7e4e17c501eeb62737)


```

Edit: Disabling Hardened Malloc made it work. You can close this issue but still I insist upon looking after it once.

**Comment by zhanghai** [comment] 2023-10-15 20:28
Duplicate of #1039.

**Closed by zhanghai** 2023-10-15 20:28 UTC

**Comment by pixincreate** [comment] 2023-10-16 03:20
Oh I did not see that!
