### ISSUE TITLE
Deleting folders with many files is abysmally slow

### ISSUE THREAD

**Issue by xeruf** [zhanghai/MaterialFiles#492] opened 2021-04-07 11:25 UTC
It took literally hours to delete a few hundred files (less than one per second) where the inbuilt file manager handled thousands within a few minutes.

**Comment by zhanghai** [comment] 2021-07-17 01:39
Likely a duplicate of #228 if this happened to you on the internal storage (aka emulated SD card). I tested deleting a folder with 1500 files and it took 9 seconds, so this should be good in the next release.

**Comment by zhanghai** [comment] 2021-07-17 01:51
Tested against an external storage folder and it seems it really takes one second to complete one file deletion request with the system, and the system DocumentsUI app has the same issue when selecting a few hundred files and pressing delete.

Although since DocumentsUI doesn't have any advanced file operation error handling, it can delete an entire folder as one operation so it's much faster in that case.

**Comment by zhanghai** [comment] 2021-07-17 01:57
I reproduce this on my Android 9.0, but on my Android 11 the speed is much faster - maybe you have to upgrade your system as this is a system issue.

**Closed by zhanghai** 2021-07-17 01:57 UTC
Labels: bug

**Comment by xeruf** [comment] 2021-07-27 10:44
I have a phone that can only run Android 8, and Android derivatives can also be behind in version.
Is there nothing you can do, maybe somehow batch them?

**Comment by zhanghai** [comment] 2021-07-27 17:32
No, the older system just takes around 1 second to handle the request to delete a single file. It is theoretically possible to make the special case of deleting one folder faster, but the file deletion logic in this app is generic to the underlying storage types, and it's hard to make it behave in a significantly different way for system external storage provider. I've suggest using the system Files app (DocumentsUI) temporarily for this type of deletion.
