### ISSUE TITLE
[SUGGESTION] Add feature to calculate checksums

### ISSUE THREAD

**Issue by ungeskriptet** [zhanghai/MaterialFiles#356] opened 2020-08-13 08:33 UTC
It would be nice if we could calculate checksums (MD5, SHA1, SHA256, etc...) in the properties menu of the file.

**Comment by SanmayJoshi** [comment] 2020-08-13 09:45
PR #303

**Comment by zhanghai** [comment] 2020-09-02 06:58
Duplicate of #48.

**Closed by zhanghai** 2020-09-02 06:58 UTC
