### ISSUE TITLE
[Feature Request] Add HASH support

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [zhanghai/MaterialFiles#850] opened 2022-08-27 16:24 UTC
Sometimes HASH is very useful when verifying the file integrity, especially after copying/transfering the file to a different medium. But it seems that this app does not support it. Basic HASHes, like `SHA256`, `SHA1`, `MD5`, `CRC32` are often used when verifying file integrity so I suggest adding those to this software.

在验证文件的完整性时，有时候HASH很有用，特别是在将文件复制/转移之后。但是，这个app似乎不支持。`SHA256`, `SHA1`, `MD5`, `CRC32`等基本HASH在验证文件完整性时被广泛使用，所以我建议在这个app中加入。

_我懒不想打中文所以中文是翻译的，不过两者均可_

**Comment by zhanghai** [comment] 2022-08-29 22:08
Duplicate of #48.

**Closed by zhanghai** 2022-08-29 22:08 UTC
