### ISSUE TITLE
Some sort of  builtin storage analyzer 

### ISSUE THREAD

**Issue by Raif1** [zhanghai/MaterialFiles#728] opened 2022-03-26 17:33 UTC
A page where my storage usage will be shown.This page will include  apps internel and sd card usage, image ,video , audio storage and sd card usage .And last but not least an apk file sorter.

**Comment by zhanghai** [comment] 2022-03-26 21:20
Duplicate of #263.

**Closed by zhanghai** 2022-03-26 21:20 UTC
