### ISSUE TITLE
[Feature Request] File Encryption & Decryption

### ISSUE THREAD

**Issue by Akhilesh-T** [zhanghai/MaterialFiles#469] opened 2021-03-20 07:00 UTC
Hi,

Currently, I'm not able to encrypt or decrypt any files using this app.

Would like to see this feature because I keep encrypted zipped files on my phone which can only be opened with a password.

Thanks!

**Comment by zhanghai** [comment] 2021-03-21 01:25
Duplicate of #267.

**Closed by zhanghai** 2021-03-21 01:25 UTC
