### ISSUE TITLE
Support Termux

### ISSUE THREAD

**Issue by linsui** [zhanghai/MaterialFiles#183] opened 2019-11-25 04:25 UTC
I found that there is a function `Open in terminal` but it doesn't work for me. Does this function support Termux? The stock file manager can access Termux home directory. Is it possible to access it in this app without root?

**Comment by zhanghai** [comment] 2019-11-25 05:07
I'd love to, but Termux currently [doesn't expose anything](https://github.com/termux/termux-app/blob/master/app/src/main/AndroidManifest.xml) for implementing this.

**Comment by zhanghai** [comment] 2019-11-25 05:08
Duplicate of #32.

**Closed by zhanghai** 2019-11-25 05:08 UTC

**Comment by sudomain** [comment] 2020-05-18 22:54
What about Termux's user defined[termux-url-opener](https://wiki.termux.com/wiki/Intents_and_Hooks)? This could be a Bash or Python script that when given an URL such as `content://com.termux.documents/document//data/data/com.termux/files/home/`  could strip away everything before `/data/data/ ...` and `cd` into that path

**Comment by zhanghai** [comment] 2020-05-19 00:49
I read the Wiki but couldn't see how `termux-url-opener` can be modified from this app. It would be confusing if user selects "Open in terminal" in Material Files, and Termux tries to download the directory as a Youtube video...

Even if the user modifies it themself, will Termux show a new UI window and keep the window after the script exits? If it actually works, I think users may just share the folder URL to the existing Termux share target, and parse it in their script.

**Comment by sudomain** [comment] 2020-05-19 02:30
>  It would be confusing if user selects "Open in terminal" in Material Files, and Termux tries to download the directory as a Youtube video...

Sorry for not being clear. The wiki suggests to put (or symlink) youtube-dl scripts to ~/bin/termux-url-opener, but I think it can handle different types of URLs. For instance an user-defined Bash script could grep the URL for `youtube.com` and then download them.The same script could also grep for an internal path such as `/sdcard/` and change into that directory using something like:

`
cd "$1"

bash
`


>will Termux show a new UI window and keep the window after the script exits?

When `termux-url-opener` is executed, Termux gets brought to the foreground and exits when the script exits. The above script will keep Termux open until the user manually exits.


> I think users may just share the folder URL to the existing Termux share target, and parse it in their script.

It could work, but currently when I press share on a directory in MaterialFiles, it only brings up options for email apps and my pdf reader. Are there plans for MaterialFiles to be able to share a path to a directory or file rather than share the directory itself?

**Comment by zhanghai** [comment] 2020-05-31 07:00
You can find the actual intent filter declaration for the wiki page you linked in [Termux's AndroidManifest.xml](https://github.com/termux/termux-app/blob/master/app/src/main/AndroidManifest.xml)

```xml
        <activity
            android:name="com.termux.filepicker.TermuxFileReceiverActivity"
            android:label="@string/application_name"
            android:taskAffinity="com.termux.filereceiver"
            android:excludeFromRecents="true"
            android:resizeableActivity="true"
            android:noHistory="true">
            <!-- Accept multiple file types when sending. -->
            <intent-filter>
                <action android:name="android.intent.action.SEND"/>
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="application/*" />
                <data android:mimeType="audio/*" />
                <data android:mimeType="image/*" />
                <data android:mimeType="message/*" />
                <data android:mimeType="multipart/*" />
                <data android:mimeType="text/*" />
                <data android:mimeType="video/*" />
            </intent-filter>
            <!-- Be more restrictive for viewing files, restricting ourselves to text files. -->
            <intent-filter tools:ignore="AppLinkUrlError">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="text/*" />
                <data android:mimeType="application/json" />
                <data android:mimeType="application/*xml*" />
                <data android:mimeType="application/*latex*" />
                <data android:mimeType="application/javascript" />
            </intent-filter>
        </activity>
```

Basically it only accepts text files for `~/bin/termux-file-editor`, and only regular files for `~/bin/termux-url-opener`. The correct MIME type for directories on Android is `vnd.android.document/directory`, or `inode/directory` on Linux, neither of which will match it and specifying an unrelated MIME type for a directory sounds too hacky for me. I would suggest opening a feature request at Termux to allow specifying a starting file path, which will be much more robust and benefit all the file managers.
