### ISSUE TITLE
Please Add Encryption Support for files and Folders

### ISSUE THREAD

**Issue by fux0r2009** [zhanghai/MaterialFiles#420] opened 2020-12-26 19:56 UTC
Hi Hai, Thanks for this amazing project !

It would be amazing if you can **add files and folders encryption/decryption (AES 256) features** like in many commercial apps (Solid Explorer etc...) It would be wonderful thanks again!

Keep up the good work :)

**Comment by zhanghai** [comment] 2020-12-27 00:29
Duplicate of #267.

**Closed by zhanghai** 2020-12-27 00:29 UTC
