### ISSUE TITLE
1024 is the only multiplier

### ISSUE THREAD

**Issue by 532910** [zhanghai/MaterialFiles#314] opened 2020-06-24 07:46 UTC
The real file size is 500 not 524 Megabytes:
![image](https://user-images.githubusercontent.com/14617699/85517341-d43cc480-b607-11ea-838a-397cfea01140.png)

**Comment by zhanghai** [comment] 2020-06-24 20:46
1024 is not the only multiplier.

**Comment by zhanghai** [comment] 2020-06-24 20:46
Duplicate of #284.

**Closed by zhanghai** 2020-06-24 20:46 UTC
