### ISSUE TITLE
Google Drive support?

### ISSUE THREAD

**Issue by ctrlbrk42** [zhanghai/MaterialFiles#705] opened 2022-03-14 19:04 UTC
Is it possible to connect Drive? I cannot figure out how, yet, but it would make this the absolute perfect file manager if so.

**Comment by zhanghai** [comment] 2022-03-15 01:52
Duplicate of #95.

**Closed by zhanghai** 2022-03-15 01:52 UTC

**Comment by rihaq** [comment] 2022-07-09 15:15
https://github.com/itszechs/DriveStream
