### ISSUE TITLE
Add # of items to help identify empty folders & move Delete button to bottom

### ISSUE THREAD

**Issue by decodering22** [zhanghai/MaterialFiles#499] opened 2021-04-15 01:22 UTC
[Feature Request]
1. Would love to see the number of items in the folder to be able to quickly distinguish empty folder to delete them like Samsungs own My files. 

2. Would like to see the delete button on the bottom. On these larger phone it is much faster to navigate to the bottom menu and delete items. 

![Screenshot_20210414-181934_My Files](https://user-images.githubusercontent.com/78891534/114800298-52608800-9d4e-11eb-8c88-b06b2fcfd5af.jpg)
![Screenshot_20210414-181943_Material Files](https://user-images.githubusercontent.com/78891534/114800302-54c2e200-9d4e-11eb-828b-9b55c8ea7756.jpg)

**Comment by zhanghai** [comment] 2021-04-15 07:27
The first FR is a duplicate of #331, so closing as duplicate.

The second FR is a design change, but design is about trade-offs and I'm not convinced about the argument. The bottom bar is currently used as the clipboard of files for copy/paste, whereas it's a standard pattern on Android to show actions in the top bar. (If you have only one file to delete you may also do it in the context menu.)

**Closed** 2021-04-15 07:27 UTC
Labels: duplicate, enhancement, question

**Comment by decodering22** [comment] 2021-04-15 07:32
If you look at most of the file managers they are incorporating the bottom area with these options because as phones have got larger it is much easier to press a button at the top than have to relocate your hand to complete an action. 

Why not provide the option to have the delete button at the bottom like AM and other apps.

**Comment by decodering22** [comment] 2021-04-15 07:38
FR #331 is months old, is there any plans to add this simple data point to help identify empty folders?
