### ISSUE TITLE
Root of SD card

### ISSUE THREAD

**Issue by Xellerate005** [zhanghai/MaterialFiles#652] opened 2022-01-04 20:21 UTC
When using material files It won't let me choose the root of the SD card and internal storage, using derpfest android 12

**Comment by ray-holmium** [comment] 2022-01-16 08:14
Same thing here on my Samsung tablet running android 12.

**Comment by zhanghai** [comment] 2022-01-16 19:31
Does changing the "Default folder" inside app settings work for you?

**Comment by ray-holmium** [comment] 2022-01-16 19:54
Negative, that also lacks a sidebar entry for the sd card. I can also attempt to manually add external storage there, but the same problem occurs. When at root of the sd card, the "use this folder" button in the google file handler is greyed out. Tapping it results in error message: "To protect your privacy choose another folder."

**Comment by zhanghai** [comment] 2022-02-08 04:07
Marking as duplicate of the request in #646.

**Closed by zhanghai** 2022-02-08 04:07 UTC
