### ISSUE TITLE
💡 Ability to open 'Copy to' URI

### ISSUE THREAD

**Issue by joe733** [zhanghai/MaterialFiles#501] opened 2021-04-16 14:24 UTC
Hi,
First of thanks a lot for this beautiful open source app. 

**Use Case:**

Suppose, I want to share some file(s) from Signal/Telegram/WhatsApp. Selecting the file & clicking on share opens up the app selector like this:

![Screenshot_20210416-175004_1.png](https://user-images.githubusercontent.com/38415384/115039890-7f4ba100-9eee-11eb-8ee7-5567b1a8fa76.png)

You see, there's an option called _copy to_ for the X-plore file manager, which helps me to open a path to save incoming file.

Is it possible to implement something like that in Material Files?

**Comment by zhanghai** [comment] 2021-04-16 16:06
Duplicate of #153.

**Closed by zhanghai** 2021-04-16 16:06 UTC
