### ISSUE TITLE
archive file cache still exists

### ISSUE THREAD

**Issue by pokegamer5547** [zhanghai/MaterialFiles#529] opened 2021-06-24 14:01 UTC
I know this bug was marked as closed in another issue but i'm still encountering it and able to reproduce it.
## Steps to reproduce:
1: Open an archive
2: open an text file in the archive using "text editor"
3: close the "text editor" and archive and check the folder. /storage/emulated/0/Android/data/me.zhanghai.android.files/cache/open_cache

**Comment by zhanghai** [comment] 2021-06-24 16:55
Which issue was this marked as closed in?

Besides that, it actually seems working as intended to me, because we can't know when it will be safe to delete these files - the app we shared these files with may try to access them any time and so that's not deterministic.

**Comment by pokegamer5547** [comment] 2021-06-25 01:17
> Which issue was this marked as closed in?

I was referring to this https://github.com/zhanghai/MaterialFiles/issues/2
> 
> Besides that, it actually seems working as intended to me, because we can't know when it will be safe to delete these files - the app we shared these files with may try to access them any time and so that's not deterministic.

Yes i understand what you mean, it does requires the app to store the file somewhere safe to make sure it loads flawlessly. But many file managers delete the cache file once the archive is not in use which isn't the case for material files in my usage.

**Comment by zhanghai** [comment] 2021-06-25 02:31
#2 is about adding the cache, not clearing it.

> once the archive is not in use

How do you define "once the archive is not in use"?

**Comment by pokegamer5547** [comment] 2021-06-25 03:30
> #2 is about adding the cache, not clearing it.
> 
> > once the archive is not in use
> 
> How do you define "once the archive is not in use"?

I'm so sorry! i thought apps could do that but i've just now tested and found many file managers doesn't delete the cache of archives when not in use. I'm truly sorry about this, it's not your app fault. 

I actually always thought when apps use content provider to share files to another app those files are stored in a private folder which only the app which is providing the file and the app which i shared with can only access. But now i understand those files are actually stored in android/data folder not in private folder.

But i noticed there is a app called EDS lite i use, which is a encrypted file container app, has the option called "force temp files" which says "use temp files instead of pipes even for read only files, some apps can't work with pipes." I'm not sure what does pipes mean but it's enabled by default and when i disable that app no longer use it's cache directory in android/data folder which it would nornally use for storing temp files for other apps. 

Ik it's too much to ask but is it possible for a implement a optional feature like that in material files? i'm not forcing you to implement since i know it's not gonna be easy as saying and any malicious app can extract the archives without consent using storage permission but i just wish the cache doesn't contain private information.

**Comment by zhanghai** [comment] 2021-06-25 03:45
It's okay. The pipe approach is actually unreliable because I assume it's referring to the Linux definition of a pipe, where the caller can read a stream of bytes from. This only works when the caller is reading the data sequentially. If the caller ever tries to write, or tries to jump back and forth with a pipe it will likely fail.

The `Android/data` directory is actually safer on Android 11+ because apps targetting 11+ will only be able to access its own sub-directory, and Play will be forcing higher target SDK year by year. That being said, you can always clear cache in the Settings App info for this app, and I believe that will also clear the `open_cache`.

**Comment by pokegamer5547** [comment] 2021-06-25 04:00
> It's okay. The pipe approach is actually unreliable because I assume it's referring to the Linux definition of a pipe, from which the caller can read a stream of bytes. This only works when the caller is reading the data sequentially. If the caller ever tries to write, or tries to jump back and forth with a pipe it will likely fail.

Oh i see, thanks for explaining! :) it sounds like it can also cause a lot of memeory usage too since if the app doesn't read the data properly then it can cause crash or re read the data multiple times.
> 
> The `Android/data` directory is actually safer on Android 11+ because apps targetting 11+ will only be able to access their own sub-directories, and Play will be forcing higher target SDK year by year. That being said, you can always clear cache in the Settings App info for this app, and I believe that will also clear the `open_cache`.

Yeah i heard about that too it's a good decision from google to do that i think. but i wonder can apps with all files access can still access the 'android/data' folder. Because i use miui and there are a lof of system apps which i don't really trust much use storage permission. And those system apps are not updated using play store but with their own appstore called GetApps. So any apps in their store will not likely gonna be forced like google play to don't use all files if not necessary.

**Comment by zhanghai** [comment] 2021-06-25 04:08
Note that even the "All file access" doesn't grant access to `Android/data` IIRC, and the DocumentsUI app is the only system app that has access to it, which is also the system file manager and provides the standard file picker UI. Material Files (currently targeting Android 10 due to a Play policy) has all file access but also relies on the trick of letting user select the `Android` directory in that picker and add that as an "External storage" for this app to access `Android/data` on Android 11+.

**Comment by pokegamer5547** [comment] 2021-06-25 04:20
> Note that even the "All file access" doesn't grant access to `Android/data` IIRC, and the DocumentsUI app is the only system app that has access to it, which is also the system file manager and provides the standard file picker UI. Material Files (currently targeting Android 10 due to a Play policy) has all file access but also relies on the trick of letting user select the `Android` directory in that picker and add that as an "External storage" for this app to access `Android/data` on Android 11+.

Ah i see, now i get it. Thankyou for telling me :) i learned something new today thanks to your information.

 I just have a one more question since i'm not a dev. You see, i use call recording in my phone with my system dialer app  and it's stores it in a folder called '/storage/emulated/0/MIUI/sound_recorder/call_rec'
But i wonder when the apps request the "media"files access permission which is to make sure apps can only access media files using scoped storage. Can apps also access call recording files with that permission since the recordings are stored in mp3 format?

**Comment by zhanghai** [comment] 2021-06-25 04:25
I'm not sure about that either (I'm not working on the Android storage team), so maybe you can ask that on some other Android forum.

**Comment by pokegamer5547** [comment] 2021-06-25 04:30
> I'm not sure about that either (I'm not working on the Android storage team), so maybe you can ask that on some other Android forum.

Oh ok then, thanks for your time clearing my doubts :) ik some of them aren't about material files but still it was fun. I'm gonna close this issue now.

**Closed** 2021-06-25 04:31 UTC
Labels: question
