### ISSUE TITLE
Add shizuku support 

### ISSUE THREAD

**Issue by akrram0** [zhanghai/MaterialFiles#1228] opened 2024-05-11 12:04 UTC
Just like Zarchiver has shizuku support to access data/obb etc it would be good for non root users

**Comment by zhanghai** [comment] 2024-05-18 21:34
Duplicate of https://github.com/zhanghai/MaterialFiles/issues/1132#issuecomment-1968428705 .

**Closed by zhanghai** 2024-05-18 21:34 UTC
