### ISSUE TITLE
allow to disable translation

### ISSUE THREAD

**Issue by aisbergde** [zhanghai/MaterialFiles#666] opened 2022-01-30 13:22 UTC
it is often hard to use translated software because of strange translations. I would prefer to use the English interface. Please implement an option to disable translation, but to allow or force English. Or just some option to select system language or any specific language.

**Comment by zhanghai** [comment] 2022-01-30 17:36
Duplicate of #293.

**Closed by zhanghai** 2022-01-30 17:36 UTC
