### ISSUE TITLE
Termux isnt detected when selecting "open with shell"

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [zhanghai/MaterialFiles#758] opened 2022-04-16 05:57 UTC
[termux](https://termux.com/), a shell emulator on android, isnt detected when selecting open in shell.

Termux在點擊使用終端開啟的時候沒被發現，顯示"未找到可以處理這操作的應用"。

**Comment by zhanghai** [comment] 2022-04-16 06:27
Duplicate of #32.

**Closed by zhanghai** 2022-04-16 06:27 UTC
