### ISSUE TITLE
Crash opening (or extracting) zip

### ISSUE THREAD

**Issue by lefuglyduck** [zhanghai/MaterialFiles#1119] opened 2024-01-30 08:05 UTC
I get this error everytime I try to open a zip file:

type: crash
osVersion: google/panther/panther:14/UQ1A.240105.004/2024011600:user/release-keys
package: me.zhanghai.android.files:34
process: me.zhanghai.android.files
processUptime: 0 + 0 ms

signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000008

backtrace:
      #00 pc 0000000000081230  /data/app/~~AnCs5gTfWrKQlt48-9qh1g==/me.zhanghai.android.files-Yk3gzOmS1WmZ8UKaQrVMaA==/lib/arm64/libarchive-jni.so (Java_me_zhanghai_android_libarchive_Archive_free+68) (BuildId: 5aac375a93b05300900d02c95f753f1f160904ba)
      #01 pc 00000000007be014  /data/app/~~AnCs5gTfWrKQlt48-9qh1g==/me.zhanghai.android.files-Yk3gzOmS1WmZ8UKaQrVMaA==/oat/arm64/base.odex (art_jni_trampoline+116)
      #02 pc 00000000008df830  /data/app/~~AnCs5gTfWrKQlt48-9qh1g==/me.zhanghai.android.files-Yk3gzOmS1WmZ8UKaQrVMaA==/oat/arm64/base.odex (p6.f.j0+1696)
      #03 pc 0000000000cb1ce0  /data/app/~~AnCs5gTfWrKQlt48-9qh1g==/me.zhanghai.android.files-Yk3gzOmS1WmZ8UKaQrVMaA==/oat/arm64/base.odex (ha.f.m+192)
      #04 pc 0000000000cb593c  /data/app/~~AnCs5gTfWrKQlt48-9qh1g==/me.zhanghai.android.files-Yk3gzOmS1WmZ8UKaQrVMaA==/oat/arm64/base.odex (ha.g.s+332)
      #05 pc 000000000133cb90  /data/app/~~AnCs5gTfWrKQlt48-9qh1g==/me.zhanghai.android.files-Yk3gzOmS1WmZ8UKaQrVMaA==/oat/arm64/base.odex (androidx.lifecycle.f1.j+544)
      #06 pc 0000000000c846ec  /data/app/~~AnCs5gTfWrKQlt48-9qh1g==/me.zhanghai.android.files-Yk3gzOmS1WmZ8UKaQrVMaA==/oat/arm64/base.odex (fj.k.o+668)
      #07 pc 0000000000dba2d4  /data/app/~~AnCs5gTfWrKQlt48-9qh1g==/me.zhanghai.android.files-Yk3gzOmS1WmZ8UKaQrVMaA==/oat/arm64/base.odex (me.zhanghai.android.files.provider.root.u.s+308)
      #08 pc 00000000008ed5e4  /data/app/~~AnCs5gTfWrKQlt48-9qh1g==/me.zhanghai.android.files-Yk3gzOmS1WmZ8UKaQrVMaA==/oat/arm64/base.odex (p6.x.call+2212)
      #09 pc 0000000000254a94  /system/framework/arm64/boot.oat (java.util.concurrent.FutureTask.run+180) (BuildId: 1348f1c03b740c7d44cc624fe7a2affb180c42a1)
      #10 pc 00000000002b3d3c  /system/framework/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor.runWorker+796) (BuildId: 1348f1c03b740c7d44cc624fe7a2affb180c42a1)
      #11 pc 00000000002b0e60  /system/framework/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor$Worker.run+64) (BuildId: 1348f1c03b740c7d44cc624fe7a2affb180c42a1)
      #12 pc 000000000015f828  /system/framework/arm64/boot.oat (java.lang.Thread.run+72) (BuildId: 1348f1c03b740c7d44cc624fe7a2affb180c42a1)
      #13 pc 00000000002109a4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: fddb1d9077c752c3861f69e7578f5207)
      #14 pc 0000000000253b3c  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+172) (BuildId: fddb1d9077c752c3861f69e7578f5207)
      #15 pc 000000000069abc8  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1416) (BuildId: fddb1d9077c752c3861f69e7578f5207)
      #16 pc 00000000000cfa2c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204) (BuildId: 683448b69f8aa065d6038085038e8da0)
      #17 pc 0000000000064770  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 683448b69f8aa065d6038085038e8da0)
```

**Comment by zhanghai** [comment] 2024-01-30 18:46
Duplicate of #1082.

**Closed by zhanghai** 2024-01-30 18:46 UTC
