### ISSUE TITLE
Feature Request Tabs

### ISSUE THREAD

**Issue by trymeouteh** [zhanghai/MaterialFiles#265] opened 2020-04-25 20:39 UTC
I like the new window feature and it is something I did not think was possible on Android. However I think a tabs feature will be really cool were you can open up multiple tabs within the same window. Many Linux file managers do this such as Nemo.

**Comment by zhanghai** [comment] 2020-04-26 00:47
Tab isn't very possible because the space for it ia used for breadcrumbs. For multi-panel, this would be a duplicate of #181.

**Closed by zhanghai** 2020-04-26 00:47 UTC
