### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Kita2345** [zhanghai/MaterialFiles#613] opened 2021-10-30 22:25 UTC
java.lang.RuntimeException: Unable to start activity ComponentInfo{me.zhanghai.android.files/me.zhanghai.android.files.viewer.image.ImageViewerActivity}: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2326)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
	at android.app.ActivityThread.access$800(ActivityThread.java:147)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5264)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at me.zhanghai.android.files.viewer.image.ImageViewerFragment.b()
	at me.zhanghai.android.files.viewer.image.ImageViewerFragment.v1()
	at me.zhanghai.android.files.viewer.image.ImageViewerFragment.V0(:2)
	at androidx.fragment.app.s.a(:5)
	at androidx.fragment.app.s.k(:8)
	at androidx.fragment.app.q.E(:8)
	at androidx.fragment.app.q.Z()
	at androidx.fragment.app.q.C(:4)
	at androidx.fragment.app.q.w(:3)
	at w0.h.onStart(:4)
	at f.h.onStart()
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
	at android.app.Activity.performStart(Activity.java:5991)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2279)
	... 10 more

**Comment by zhanghai** [comment] 2022-02-07 07:37
Looks like a duplicate of #590.

**Closed by zhanghai** 2022-02-07 07:37 UTC
Labels: bug, duplicate
