### ISSUE TITLE
[Feature Request] Manually Language Changing Option

### ISSUE THREAD

**Issue by GoRaN909** [zhanghai/MaterialFiles#548] opened 2021-08-08 14:50 UTC
Hello, i saw this app on google paly when i search to file manager i love this one have many great feature and easy to use.
The only thing that missing in this application there is no an option in the app setting to manually change the language of app that's will be great if you add an option and let user to manually change app interface language instead of change the device language in system settings.

Thanks

**Comment by zhanghai** [comment] 2021-08-08 14:52
But why? I assume users are supposed to pick the language that they want to use in system Settings.

**Comment by GoRaN909** [comment] 2021-08-08 14:59
> But why? I assume users are supposed to pick the language that they want to use in system Settings.
> 
> There are also a bunch of small things that might be to get right without restarting the app, which happens on language change.

Because in android all languages not supported yet for example man native language is Kurdish it's not support yet by google Android OS but it's available on Google Translate and many other google services, I interested to translate this app to my language but if i do that no one can use it because there are no Kurdish language in Android System till now :(

**Comment by zhanghai** [comment] 2022-02-10 23:06
Duplicate of #293.

**Closed by zhanghai** 2022-02-10 23:06 UTC
Labels: duplicate, enhancement
