### ISSUE TITLE
[Feature Request] Add ftp browsing support

### ISSUE THREAD

**Issue by AhsanBulbul00** [zhanghai/MaterialFiles#502] opened 2021-04-17 00:55 UTC
When using Material file manager, it can easily start ftp server. But it can't browse ftp of other devices. It would be great to see ftp support for browsing, as it's a common protocol.

**Comment by zhanghai** [comment] 2021-04-17 03:23
Duplicate of #213.

**Closed by zhanghai** 2021-04-17 03:23 UTC
