### ISSUE TITLE
[Feature Request] Recent files

### ISSUE THREAD

**Issue by sumitautade** [zhanghai/MaterialFiles#635] opened 2021-12-13 12:06 UTC
Would love to see a recent files section where all the recently created files appear. This feature is available on Simple File Manager (by Simple Mobile Tools) and is the only thing holding me back from completely switching to Material Files. Please consider this. Thanks.

**Comment by zhanghai** [comment] 2021-12-13 12:31
Duplicate of #146

**Closed by zhanghai** 2021-12-13 12:31 UTC
