### ISSUE TITLE
“名称” misplaced when editing WebDAV server

### ISSUE THREAD

**Issue by MkQtS** [zhanghai/MaterialFiles#1139] opened 2024-02-28 01:09 UTC
![image](https://github.com/zhanghai/MaterialFiles/assets/81752398/2505a375-7652-4999-be57-16f98c4f3353)

This happens when the automatically generated name is too long. No such problem with user entered long name.

**Comment by zhanghai** [comment] 2024-02-28 04:37
Duplicate of https://github.com/material-components/material-components-android/issues/3874 - not much this app can do...

**Closed by zhanghai** 2024-02-28 04:37 UTC

**Comment by zhanghai** [comment] 2024-02-28 04:39
By the way is the WebDAV functionality working for you and your server(s)? I don't have a WebDAV server and couldn't test things like writing files...

**Comment by zhanghai** [comment] 2024-03-01 02:52
Do you have the error message (or even stacktrace in logcat) for the failed modifications under the root path?

**Comment by zhanghai** [comment] 2024-03-02 01:51
I couldn't reproduce this with other WebDAV servers I tried (`chezdav`, `rclone serve webdav`), so maybe Jianguoyun has some non-standard behavior for root directory? The servers I tried each have their own bugs as well. WebDAV is such a mess...

**Comment by zhanghai** [comment] 2024-03-02 01:52
By the way, were you able to see the correct last modified time for your files? Or are they always in year 1969/1970?

**Comment by zhanghai** [comment] 2024-03-03 03:18
Could you try the APK from https://github.com/zhanghai/MaterialFiles/actions/runs/8127304215 ?

**Comment by zhanghai** [comment] 2024-03-03 20:42
Thank you for testing this out! I'm planning a new release in the upcoming weeks with this feature.
