### ISSUE TITLE
"Material Files keeps stopping" when opening a picture

### ISSUE THREAD

**Issue by PrSunflower** [zhanghai/MaterialFiles#370] opened 2020-09-08 12:00 UTC
### Problem

The app works great but strangely it crashes 100% of the time when opening **one specific picture**. If I try multiple times my system tells me "**Material Files keeps stopping**".

Browsing for the file:

![Screenshot_20200915-085630](https://user-images.githubusercontent.com/59576952/93603909-f5257380-f9c4-11ea-8cdc-86bf2bca9617.png)

Opening the file:

![Screenshot_20200915-085951](https://user-images.githubusercontent.com/59576952/93603973-0c646100-f9c5-11ea-91f5-1459dfd7418a.png)

![Screenshot_20200915-085954](https://user-images.githubusercontent.com/59576952/93604017-1a19e680-f9c5-11ea-8ead-1b0879485123.png)

<br>

Selecting the next picture "Majuscules_accentuees.jpg", it opens correctly but sliding to show the previous picture crashes again:

![Screenshot_20200915-090023](https://user-images.githubusercontent.com/59576952/93604223-5fd6af00-f9c5-11ea-90d1-71b94244faa1.png)

<br>

###  System info

Nokia 7.2 running Android 10 ("stock" Android).

App version: 1.1.2 (20)

<br>

### Additional info

I could have chosen to set another app as my default Photo viewer, but I am using [Simple Gallery Pro](https://github.com/SimpleMobileTools/Simple-Gallery) and it cannot open images in directories it is not scanning. That's why I need to keep Material Files as my default photo viewer.

**Comment by EmilVogt** [comment] 2020-09-14 22:08
Does it happen when you open the folder of pictures in the explorer or when you open a picture in the built-in picture viewer?
In the former case, it might be related to issue#283. Looks like lazy loading of thumbnails is not working.

**Comment by PrSunflower** [comment] 2020-09-15 07:05
@EmilVogt Hi, it happens when I am opening a picture with the built-in picture viewer.

I have read your description of issue #228, according to my usage I don't even remember seeing a spinning wheel. 😄 Maybe for like 1 second only because Material Files is pretty fast on my phone. I don't use an SD card though, only Internal memory so that could be why.

### Additional info on the issue

Wow surprising! 😮 I am trying to replicate the issue by opening pictures inside a folder that contains 2000+ pictures and everything works fine, each picture is opening neatly with the built-in picture viewer.

However the app crashes when opening **one specific picture** inside a folder that contains only 18 pictures. I'll be describing this later during the day.

**Comment by PrSunflower** [comment] 2020-09-18 13:43
I have updated the title and the description of the issue to better describe it. Really strange problem!

**Comment by zhanghai** [comment] 2020-09-19 09:40
If it is only happening for one file, could you share the original image  file here? Likely something particular about that file triggered this.

**Comment by PrSunflower** [comment] 2020-09-19 15:55
@zhanghai Yes, I have been trying to replicate the issue and so far it happens only for this picture:

![Majuscules accentuees Alt Codes](https://user-images.githubusercontent.com/59576952/93670711-ae577c80-fa9d-11ea-90cd-dbed53ab874b.jpg)

Just in case GitHub modifies attached pictures, here's another link to the same file: https://cryptpad.fr/file/#/2/file/pUmE1S0zhKupDowTowYZVtBv/

**Comment by zhanghai** [comment] 2020-09-19 20:44
The image on GitHub seems indeed compressed, it is only 4.05 MB instead of 7.97 MB when downloaded from CryptPad. However, neither of the two images triggered a crash for me on OnePlus 5 Android 9.0. The md5sum for the 7.97 MB image is `22b2a03da02cec1f484e6b0393fff6e7` on my side.

Meanwhile, does opening that image file crash other image viewers on your phone? I'm suspecting it might be a native crash in your Android platform when decoding this specific image file.

**Comment by PrSunflower** [comment] 2020-09-20 15:34
@zhanghai Yes it is confirmed, GitHub compresses images as the original is 7.97 MB. 

### MD5 sums on my side

- Original file: `fdaba3733f412b2ad4a94f375dbb2a6b`
- Copy+paste in Material Files: `fdaba3733f412b2ad4a94f375dbb2a6b`
- Download form Cryptpad: `22b2a03da02cec1f484e6b0393fff6e7`

Oh no! Cryptpad has changed the file 😅 (although they have exactly the same size, `7,968,505 bytes`)

### Trying again...

I am uploading it again inside a 7-Zip archive: https://cryptpad.fr/file/#/2/file/77YBlREivMzkcEM8mmxjdKuu/

When I downloaded it from Cryptpad, the extracted file's MD5 is `fdaba3733f412b2ad4a94f375dbb2a6b`. Seems good.

<br>

Thank you for your time!

**Comment by zhanghai** [comment] 2020-09-20 20:10
This seems to only happen on Android 10 but not Android 9, and I had to reproduce it in an emulator:

```
2020-09-20 13:07:04.268 6997-6997/me.zhanghai.android.files D/AndroidRuntime: Shutting down VM
2020-09-20 13:07:04.406 6997-6997/me.zhanghai.android.files E/AndroidRuntime: FATAL EXCEPTION: main
    Process: me.zhanghai.android.files, PID: 6997
    java.lang.RuntimeException: Canvas: trying to draw too large(192000000bytes) bitmap.
        at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
        at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
        at coil.drawable.CrossfadeDrawable.draw(CrossfadeDrawable.kt:90)
        at android.widget.ImageView.onDraw(ImageView.java:1416)
        at android.view.View.draw(View.java:21421)
        at android.view.View.updateDisplayListIfDirty(View.java:20298)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4372)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4345)
        at android.view.View.updateDisplayListIfDirty(View.java:20258)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4372)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4345)
        at android.view.View.updateDisplayListIfDirty(View.java:20258)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4372)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4345)
        at android.view.View.updateDisplayListIfDirty(View.java:20258)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4372)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4345)
        at android.view.View.updateDisplayListIfDirty(View.java:20258)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4372)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4345)
        at android.view.View.updateDisplayListIfDirty(View.java:20258)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4372)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4345)
        at android.view.View.updateDisplayListIfDirty(View.java:20258)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4372)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4345)
        at android.view.View.updateDisplayListIfDirty(View.java:20258)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4372)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4345)
        at android.view.View.updateDisplayListIfDirty(View.java:20258)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3610)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3418)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2755)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:725)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

Somehow the image decoder thinks the image has more than 192MB after decoding 😕

**Comment by zhanghai** [comment] 2020-09-20 21:22
After taking a closer look, what happened on the emulator seems actually correct looking at AOSP source for `RecordingCanvas`. I attached to the app process for debugging on both my OnePlus Android 9.0 and the emulator Android 10.0, and found out both returned a 192MB bitmap. It is just that OnePlus's Android somehow allowed apps to draw bitmaps greater than 100MB but stock Android doesn't allow it. The fix for this would be using [SubsamplingScaleImageView](https://github.com/davemorrissey/subsampling-scale-image-view) for large images, which is currently already used for images with an aspect ratio greater than 2.

**Comment by zhanghai** [comment] 2020-09-20 21:27
I've locally tested that the fix works, and it will be available in the next app release.

**Closed** 2020-09-20 21:26 UTC
Labels: bug

**Comment by PrSunflower** [comment] 2020-09-22 12:19
@zhanghai  Wooooo! 😮

You have replied and investigated the issue very quickly and with a lot of determination! Thanks a lot for that!

From a user's perspective, it's really awesome to see a developer care that much about sharing and improving his app. Thank you very much, 💚 Free Software!
