### ISSUE TITLE
Memory Overflow Crash When Extracting zip

### ISSUE THREAD

**Issue by MichaelDevon** [zhanghai/MaterialFiles#1125] opened 2024-02-08 22:05 UTC
```
type: crash
osVersion: google/shiba/shiba:14/UQ1A.240205.004/2024020500:user/release-keys
uid: 10168 (u:r:untrusted_app:s0:c168,c256,c512,c768)
cmdline: me.zhanghai.android.files
processUptime: 30s

signal: 11 (SIGSEGV), code 9 (SEGV_MTESERR), faultAddr 900d688a38a4628
threadName: pool-3-thread-1
MTE: enabled

backtrace:
    /data/app/~~scrwBLyXd14JQLEH_tvojw==/me.zhanghai.android.files-xgqXvKz3IhukoYoY8OyFaw==/lib/arm64/libarchive-jni.so (Java_me_zhanghai_android_libarchive_Archive_free+64, pc 8122c)
    /data/app/~~scrwBLyXd14JQLEH_tvojw==/me.zhanghai.android.files-xgqXvKz3IhukoYoY8OyFaw==/oat/arm64/base.odex (art_jni_trampoline+116, pc 7bb744)
    /data/app/~~scrwBLyXd14JQLEH_tvojw==/me.zhanghai.android.files-xgqXvKz3IhukoYoY8OyFaw==/oat/arm64/base.odex (p6.f.j0+1696, pc 8dd0c0)
    /data/app/~~scrwBLyXd14JQLEH_tvojw==/me.zhanghai.android.files-xgqXvKz3IhukoYoY8OyFaw==/oat/arm64/base.odex (ha.f.m+192, pc caf3a0)
    /data/app/~~scrwBLyXd14JQLEH_tvojw==/me.zhanghai.android.files-xgqXvKz3IhukoYoY8OyFaw==/oat/arm64/base.odex (ha.d.k+300, pc 150658c)
    /data/app/~~scrwBLyXd14JQLEH_tvojw==/me.zhanghai.android.files-xgqXvKz3IhukoYoY8OyFaw==/oat/arm64/base.odex ([DEDUPED] ha.d.a+36, pc 1506094)
    /data/app/~~scrwBLyXd14JQLEH_tvojw==/me.zhanghai.android.files-xgqXvKz3IhukoYoY8OyFaw==/oat/arm64/base.odex (me.zhanghai.android.files.provider.remote.f1.j+1528, pc 1408858)
    /data/app/~~scrwBLyXd14JQLEH_tvojw==/me.zhanghai.android.files-xgqXvKz3IhukoYoY8OyFaw==/oat/arm64/base.odex (fj.k.o+668, pc c81dac)
    /data/app/~~scrwBLyXd14JQLEH_tvojw==/me.zhanghai.android.files-xgqXvKz3IhukoYoY8OyFaw==/oat/arm64/base.odex (ha.g.v+856, pc cb3fd8)
    /data/app/~~scrwBLyXd14JQLEH_tvojw==/me.zhanghai.android.files-xgqXvKz3IhukoYoY8OyFaw==/oat/arm64/base.odex (c2.h.j+1640, pc 13678d8)
    /data/app/~~scrwBLyXd14JQLEH_tvojw==/me.zhanghai.android.files-xgqXvKz3IhukoYoY8OyFaw==/oat/arm64/base.odex (fj.k.o+668, pc c81dac)
    /data/app/~~scrwBLyXd14JQLEH_tvojw==/me.zhanghai.android.files-xgqXvKz3IhukoYoY8OyFaw==/oat/arm64/base.odex (me.zhanghai.android.files.provider.root.u.v+320, pc db8020)
    /data/app/~~scrwBLyXd14JQLEH_tvojw==/me.zhanghai.android.files-xgqXvKz3IhukoYoY8OyFaw==/oat/arm64/base.odex (y6.j.a+200, pc a1dd48)
    /data/app/~~scrwBLyXd14JQLEH_tvojw==/me.zhanghai.android.files-xgqXvKz3IhukoYoY8OyFaw==/oat/arm64/base.odex (y6.j.d+124, pc a1e43c)
    /data/app/~~scrwBLyXd14JQLEH_tvojw==/me.zhanghai.android.files-xgqXvKz3IhukoYoY8OyFaw==/oat/arm64/base.odex (y6.n.e+144, pc a1f040)
    /data/app/~~scrwBLyXd14JQLEH_tvojw==/me.zhanghai.android.files-xgqXvKz3IhukoYoY8OyFaw==/oat/arm64/base.odex (p6.f.s0+412, pc 8e31fc)
    /data/app/~~scrwBLyXd14JQLEH_tvojw==/me.zhanghai.android.files-xgqXvKz3IhukoYoY8OyFaw==/oat/arm64/base.odex (v9.f.b+4140, pc f79fac)
    /data/app/~~scrwBLyXd14JQLEH_tvojw==/me.zhanghai.android.files-xgqXvKz3IhukoYoY8OyFaw==/oat/arm64/base.odex (e.u.run+3344, pc 63e090)
    /system/framework/arm64/boot.oat (java.util.concurrent.Executors$RunnableAdapter.call+68, pc 1b9a84)
    /system/framework/arm64/boot.oat (java.util.concurrent.FutureTask.run+180, pc 254a94)
    /system/framework/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor.runWorker+796, pc 2b3d3c)
    /system/framework/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor$Worker.run+64, pc 2b0e60)
    /system/framework/arm64/boot.oat (java.lang.Thread.run+72, pc 15f828)
    /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612, pc 2109a4)
    /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+172, pc 253b3c)
    /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1416, pc 69abc8)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc d006c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64db0)
```

**Comment by firefoxlover** [comment] 2024-02-13 10:43
```
type: crash
osVersion: google/bluejay/bluejay:14/UQ1A.240205.002/2024020500:user/release-keys
package: me.zhanghai.android.files:34
process: me.zhanghai.android.files
processUptime: 0 + 0 ms
installer: org.fdroid.basic

signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000008

backtrace:
      #00 pc 0000000000081230  /data/app/~~JGdmlj9M2WmK9OoaUI6wUg==/me.zhanghai.android.files-LiQF-_HR4PY13pd20NVFcw==/lib/arm64/libarchive-jni.so (Java_me_zhanghai_android_libarchive_Archive_free+68) (BuildId: 5aac375a93b05300900d02c95f753f1f160904ba)
      #01 pc 00000000007be014  /data/app/~~JGdmlj9M2WmK9OoaUI6wUg==/me.zhanghai.android.files-LiQF-_HR4PY13pd20NVFcw==/oat/arm64/base.odex (art_jni_trampoline+116)
      #02 pc 00000000008df830  /data/app/~~JGdmlj9M2WmK9OoaUI6wUg==/me.zhanghai.android.files-LiQF-_HR4PY13pd20NVFcw==/oat/arm64/base.odex (p6.f.j0+1696)
      #03 pc 0000000000cb1ce0  /data/app/~~JGdmlj9M2WmK9OoaUI6wUg==/me.zhanghai.android.files-LiQF-_HR4PY13pd20NVFcw==/oat/arm64/base.odex (ha.f.m+192)
      #04 pc 0000000000cb593c  /data/app/~~JGdmlj9M2WmK9OoaUI6wUg==/me.zhanghai.android.files-LiQF-_HR4PY13pd20NVFcw==/oat/arm64/base.odex (ha.g.s+332)
      #05 pc 000000000133cb90  /data/app/~~JGdmlj9M2WmK9OoaUI6wUg==/me.zhanghai.android.files-LiQF-_HR4PY13pd20NVFcw==/oat/arm64/base.odex (androidx.lifecycle.f1.j+544)
      #06 pc 0000000000c846ec  /data/app/~~JGdmlj9M2WmK9OoaUI6wUg==/me.zhanghai.android.files-LiQF-_HR4PY13pd20NVFcw==/oat/arm64/base.odex (fj.k.o+668)
      #07 pc 0000000000dba2d4  /data/app/~~JGdmlj9M2WmK9OoaUI6wUg==/me.zhanghai.android.files-LiQF-_HR4PY13pd20NVFcw==/oat/arm64/base.odex (me.zhanghai.android.files.provider.root.u.s+308)
      #08 pc 00000000008ed5e4  /data/app/~~JGdmlj9M2WmK9OoaUI6wUg==/me.zhanghai.android.files-LiQF-_HR4PY13pd20NVFcw==/oat/arm64/base.odex (p6.x.call+2212)
      #09 pc 0000000000254a94  /system/framework/arm64/boot.oat (java.util.concurrent.FutureTask.run+180) (BuildId: 1348f1c03b740c7d44cc624fe7a2affb180c42a1)
      #10 pc 00000000002b3d3c  /system/framework/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor.runWorker+796) (BuildId: 1348f1c03b740c7d44cc624fe7a2affb180c42a1)
      #11 pc 00000000002b0e60  /system/framework/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor$Worker.run+64) (BuildId: 1348f1c03b740c7d44cc624fe7a2affb180c42a1)
      #12 pc 000000000015f828  /system/framework/arm64/boot.oat (java.lang.Thread.run+72) (BuildId: 1348f1c03b740c7d44cc624fe7a2affb180c42a1)
      #13 pc 00000000002109a4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: fddb1d9077c752c3861f69e7578f5207)
      #14 pc 0000000000253b3c  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+172) (BuildId: fddb1d9077c752c3861f69e7578f5207)
      #15 pc 000000000069abc8  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1416) (BuildId: fddb1d9077c752c3861f69e7578f5207)
      #16 pc 00000000000cfa2c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204) (BuildId: 8bc16426785f69835644a00e95964c1d)
      #17 pc 0000000000064770  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 8bc16426785f69835644a00e95964c1d)
```

**Comment by zhanghai** [comment] 2024-03-04 08:19
Duplicate of #1065.

**Closed by zhanghai** 2024-03-04 08:19 UTC
