### ISSUE TITLE
Rename popup text input can get really small

### ISSUE THREAD

**Issue by Nonononoki** [zhanghai/MaterialFiles#216] opened 2019-12-23 06:35 UTC
The text input popup can get really small on a 720p device. It seems that the height is dependent on available screen height, shrinks when keyboard is shown.
![Screenshot_20191223-073006_Material_Files](https://user-images.githubusercontent.com/11612388/71340332-c756ef80-2556-11ea-8efb-eb7ba59d9e09.png)
![Screenshot_20191223-073000_Material_Files](https://user-images.githubusercontent.com/11612388/71340337-cb830d00-2556-11ea-9e0d-b9c4271a033c.png)

**Comment by linsui** [comment] 2019-12-24 04:05
duplicate of #214 ?

**Comment by zhanghai** [comment] 2019-12-24 06:03
Yes, duplicate of #214 and #210.

**Closed by zhanghai** 2019-12-24 06:03 UTC
