### ISSUE TITLE
Image viewer sftp broken

### ISSUE THREAD

**Issue by amorrn** [zhanghai/MaterialFiles#1171] opened 2024-03-20 10:11 UTC
Hi, as of the 1.7.0 update viewing images from a remote sftp server no longer works. It produces a java error. This is working OK in 1.6.2. Please see attached screenshot.
![Screenshot_2024-03-20-11-04-41-64_29c0a1e3aaa5223e1ffcd3f9ab52a346](https://github.com/zhanghai/MaterialFiles/assets/16481524/6b70219e-d1a9-4508-94dc-f24db69ab170)

**Comment by zhanghai** [comment] 2024-03-20 16:57
Duplicate of #1154.

**Closed by zhanghai** 2024-03-20 16:57 UTC
Labels: bug, duplicate
