### ISSUE TITLE
Material Design and black night mode not working together

### ISSUE THREAD

**Issue by gege-d** [zhanghai/MaterialFiles#1172] opened 2024-03-20 11:42 UTC
Since the last update Material Design and black night mode do not work together anymore. They work individually, but if both are switched on, none of them is really active.
I tried this on two different Samsung devices with Android 12 and 13.

**Comment by zhanghai** [comment] 2024-03-20 16:52
Duplicate of #1151.

**Closed by zhanghai** 2024-03-20 16:52 UTC
