### ISSUE TITLE
Share files or folders directly and locally to another Android device

### ISSUE THREAD

**Issue by xxxxq64** [zhanghai/MaterialFiles#333] opened 2020-07-20 02:35 UTC
Hi,

I like Material Files and it looks nice.

But I haven't found a feature that allows me to transfer my files or folders locally and wirelessly directly to another Android device.

---
Here is an example of how it should be.

I have a Realme X50 Pro (Android 10) and a Xiaomi Mi 9 (Android 10) both have the same Material Files version installed. The X50 Pro device is connected to the Mi 9 local Wi-Fi hotspot.

Yes, on my Mi 9 device I can easily create a Wi-Fi hotspot (2.4 GHz or 5 GHz) in the settings without a SIM card. Just like my 4G mobile router.

Now I select a file or folder and send it wirelessly and directly to other Android devices. Not to forget that the timestamp under "Last Modified" is the same after the transfer.

---
Can you add such a function?

If possible, it should not only support Wi-Fi hotspot, but also Wi-Fi Direct and Bluetooth.

**Comment by zhanghai** [comment] 2020-07-20 08:06
This seems a duplicate of your issue #334 - I don't have a plan to support transfering files via Wi-Fi direct/bluetooth, because that functionality itself requires a lot of effort and can be the subject of a brand new app. If you are using one device as a hotspot, you may start a FTP server on it with Material Files and visit the FTP via Chrome on the other device. You may also check out [Android's new nearby sharing](https://www.androidpolice.com/2020/07/18/how-to-use-androids-airdrop-like-nearby-share-feature/), which I recently saw in the news.

**Closed by zhanghai** 2020-07-20 08:06 UTC

**Comment by xxxxq64** [comment] 2020-07-20 13:02
Thanks for the tips with the FTP server.



I tried it in Chrome, but it only supports files and no folders.



Unfortunately the timestamp for "Date Modified" from the same file is not the same after transferring it to the other Android device.  It always uses the current time.



The UI of this FTP server in Chrome does not look nice and it does not support multiple file selection.



Android Nearby Share have not tested. But other apps (e.g ShareMe) that are similar and here is only the problem with the timestamp and it doesn't support "Wi-Fi hotspot only (2.4 GHz or 5 GHz)".

The advantage of the Wi-Fi hotspot is that it is local, without Bluetooth and does not require any other additional permissions such as location.
