### ISSUE TITLE
Support Termux

### ISSUE THREAD

**Issue by xmha97** [zhanghai/MaterialFiles#551] opened 2021-08-09 20:25 UTC
Hi, please support Termux
![Screenshot_2021-08-10-00-54-17-818_me.zhanghai.android.files.jpg](https://user-images.githubusercontent.com/23485114/128769572-f2e5bb7d-99be-441d-93bc-d88f3bf6ead4.jpg)

**Comment by zhanghai** [comment] 2021-08-09 22:47
Duplicate of #32.

**Closed by zhanghai** 2021-08-09 22:47 UTC
