### ISSUE TITLE
[Feature Request] When clicking on Address bar I can view/ change current path

### ISSUE THREAD

**Issue by prateekmedia** [zhanghai/MaterialFiles#404] opened 2020-12-01 04:37 UTC
This feature is very handy, like If I want to go to specific path or I want to connect to an Ftp server, I can just click on address bar and type the ftp server name and then connect to it.

 I have used this option in Solid Explorer that's why I wanted it.

**Comment by zhanghai** [comment] 2020-12-01 05:25
Duplicate of #367

**Closed by zhanghai** 2020-12-01 05:25 UTC
