### ISSUE TITLE
Material You Colors Messed Up After Update

### ISSUE THREAD

**Issue by Henry-Hiles** [zhanghai/MaterialFiles#1183] opened 2024-03-26 20:20 UTC
Hello, I just updated the app, and now all the material colors are way darker and stuff. If this isn't known I can include screenshots, and if it was intentional, then: why?

**Comment by zhanghai** [comment] 2024-03-26 22:47
Not intentional by me. Duplicate of #1173 and I haven't got time to look into it.

**Comment by zhanghai** [comment] 2024-03-26 22:48
Ah yes, if your device isn't Samsung having your screenshots would also be helpful for me to investigate.

**Closed by zhanghai** 2024-03-26 22:47 UTC

**Comment by Henry-Hiles** [comment] 2024-03-26 22:51
Its not Samsung, here are the screenshots, material files vs other mateiral you apps:
![Screenshot_20240326-185111_QWeather](https://github.com/zhanghai/MaterialFiles/assets/71790868/6da2d9ad-ffba-4ece-b59a-aad17bf8b5e6)
![Screenshot_20240326-185058_Moshidon](https://github.com/zhanghai/MaterialFiles/assets/71790868/41aeded9-7730-40c5-b13a-53375a2175e1)
![Screenshot_20240326-185052_Material Files](https://github.com/zhanghai/MaterialFiles/assets/71790868/b2060e13-36dc-4571-9734-13592d031751)

**Comment by zhanghai** [comment] 2024-03-29 05:24
What is your device model and Android version?

**Comment by Henry-Hiles** [comment] 2024-03-29 13:05
Device model shouldn't matter, but its a Redmi Note 8. Its running a custom ROM called CherishOS at android 13.

**Comment by Henry-Hiles** [comment] 2024-04-05 14:47
I remember another app did this, I can send the commit they had to fix it maybe

**Comment by Henry-Hiles** [comment] 2024-04-05 14:50
Nvm it was 6 months ago, I can't find the commit but here is the issue if it helps: https://codeberg.org/Gaukler_Faun/FOSS_Browser/issues/1104

**Comment by Henry-Hiles** [comment] 2024-04-05 19:00
Its possible it was this commit: https://codeberg.org/Gaukler_Faun/FOSS_Browser/commit/639d70f79137a9b02e767a1f17ba09fb53a3b660

**Comment by Henry-Hiles** [comment] 2024-05-10 15:22
Figured it out (still annoyed this wasn't reopened, it should have been). It was caused by the material components update, and is purposeful by android. You can use https://github.com/Mahmud0808/ColorBlendr to fix it, but it needs root access.
