### ISSUE TITLE
Input fields gets clipped

### ISSUE THREAD

**Issue by nhfo** [zhanghai/MaterialFiles#298] opened 2020-05-27 05:04 UTC
Input field in dialogues gets clipped when keyboard is visible,  new file dialogue looks like in below screenshot for example.

![Screenshot_20200527-072637-01](https://user-images.githubusercontent.com/37780254/82978843-33e68680-9fee-11ea-847c-ab9cca894b71.jpeg)

Same issue can be seen in other dialogue boxes too, like shortcut edit, new folder, rename.

Device Name: ONE E1003 OnePlus X
Android Version: 6.0.1
Screen class: normal
Density class: xxhdpi
Total Width (px): 1080
Total Height (px): 1920
App-usable Width (px): 1080
App-usable Height (px): 1776
Width (dp): 360
Height (dp): 640
Smallest DP: 360
Long or Wide: No
Screen DPI: 480

**Comment by zhanghai** [comment] 2020-05-27 08:39
This is a duplicate of #250. I'm actually curious why this is happening, because I can't reproduce this even with vertical split screen pushing the window to minimum height.

By the way, how does the stock DocumentsUI create file dialog look like with IME open?

**Closed** 2020-05-27 08:39 UTC

**Comment by nhfo** [comment] 2020-05-27 11:55
> I can't reproduce this even with vertical split screen pushing the window to minimum height.

Does it look the same if you rename a file in lower split?

It seems whatever content that is visible is scrollable.

I don't know how it works in Android, but is there too much padding and no minimum height set? 

I can get you pictures with layout bounds visible later.

**Comment by zhanghai** [comment] 2020-05-27 18:58
Yes, it looks the same:

![Screenshot_20200527-115506](https://user-images.githubusercontent.com/4469895/83060949-12e35d00-a011-11ea-918d-3a8d16959247.jpg)

I'm actually wondering if this is an Android 6.0 bug, because mine is 9.0, and another two reports mentioned 6.0 as well.

**Comment by nhfo** [comment] 2020-10-27 20:32
I noticed that file permissions > SE Linux context field does not get clipped. I wonder is somehow it is related to floating button. It goes behind in this case, but otherwise remain fully visible.
