### ISSUE TITLE
Black theme not working any more after updating to 1.7.0

### ISSUE THREAD

**Issue by D3SOX** [zhanghai/MaterialFiles#1151] opened 2024-03-12 00:42 UTC
I'm using CalyxOS (Android 14) on my Pixel 8 Pro.
I have enabled the setting to use a black background with the dark theme in the system settings. Furthermore, I think that's a patch which is also present in LineageOS because GrapheneOS didn't have it.

With the previous version it either used the black from my system as background color or the toggle “Black night mode” in settings worked accordingly. But now it's using a gray and when I enable “Black night mode” it falls back to the blue Material Design 2 theme.

I could also test this on my OnePlus 8T running LineageOS that's on Android 13 if needed.

**Comment by zhanghai** [comment] 2024-03-12 00:49
I'm using stock OxygenOS Android 14 on my OnePlus 12 and it's working fine for me. I checked on OxygenOS Android 9 on my OnePlus 5 and it's working fine as well. I wasn't able to reproduce your bug on a Pixel 2 API 34 emualtor either.

Maybe you had a recent CalyxOS update that broke apps? And does downgrading Material Files fix the issue for you?

**Comment by D3SOX** [comment] 2024-03-12 01:19
This is the toggle I'm talking about

![image](https://github.com/zhanghai/MaterialFiles/assets/24937357/59411788-c9a3-48e6-b410-b23eec72ba78)

https://github.com/zhanghai/MaterialFiles/assets/24937357/fad6421b-c0c3-41e9-b0e6-8326738bd414

**Comment by zhanghai** [comment] 2024-03-12 04:21
Oh nevermind I reproduced it, it's probably due to resource shrinking in release mode which got more agressive without me noticing...

**Comment by zhanghai** [comment] 2024-03-12 04:36
This issue has been fixed in code now. I'll wait for a few more days for people to report other potential issues and make a hot-fix release later this week.

**Closed by zhanghai** 2024-03-12 04:36 UTC
Labels: bug

**Comment by solargazr** [comment] 2024-03-12 12:01
I  don't know if this is related, but custom accent colors aren't working either. Or if that's intentional, since the feature will be deprecated in future release?

**Comment by zhanghai** [comment] 2024-03-13 06:11
That's not intentional and I believe it's this same resource shrinking issue.
