### ISSUE TITLE
Deleting Enhancement

### ISSUE THREAD

**Issue by GithubContributor832** [zhanghai/MaterialFiles#740] opened 2022-04-01 22:08 UTC
Every time I delete a file on my custom ROM with this app it's gone but still in the Downloads tab of the very buggy default com.android.documentsui. It's highly annoying and your the best open source file manager app and compete with proprietary. However, with lets say Amaze file manager this is not an issue. I have to go about manually removing deleted but shown files in the crappy default file app with custom ROMs. If you could fix this it be great. Thanks for all your hard work.

**Comment by zhanghai** [comment] 2022-04-01 23:18
Material Files actually do have code taking care of that and it works for me (just checked on my OnePlus 5 running Android 9.0) and probably a lot of users.

Could you share your phone model, system version and app version? And what is the exact steps to reproduce the issue? For me I tried:

1. Create a file under Downloads/ in Material Files.
2. It showed up in DocumentsUI Downloads.
3. Deleted that file in Material Files.
4. The file disappeared in DocumentsUI as well.

**Comment by GithubContributor832** [comment] 2022-04-01 23:24
Galaxy S9 plus, efoundation ROM 0.23 latest, and fdroid version 1.4.1. Same steps as you but downloaded file and deleted in your app and stayed in documentsui.

**Comment by GithubContributor832** [comment] 2022-04-01 23:53
Keep in mind if I follow your steps with creating a folder in your app and delete with your app it disappears in documentsui. It happens when I sideload and download other files.

**Comment by zhanghai** [comment] 2022-04-02 05:54
What version of Android is `efoundation ROM 0.23 latest` based on? I did a quick search but couldn't find out.

Meanwhile I tried downloading your GitHub avatar in Chrome, it appear in DocumentsUI, and successfully disappeared when I deleted it in Material Files, on my OnePlus 5 running Android 9.0.

**Comment by GithubContributor832** [comment] 2022-04-02 06:00
https://images.ecloud.global/dev/star2lte/

OK thanks but yeah I did.as you to no win.

**Comment by GithubContributor832** [comment] 2022-04-02 06:05
Android 10.

**Comment by zhanghai** [comment] 2022-04-02 10:49
The issue isn't reproducible on Android 9 and 13, but is indeed reproducible on Android 10 emulator. I'll look into what went wrong.

**Comment by zhanghai** [comment] 2022-04-02 11:34
The relevant AOSP fix is https://cs.android.com/android/_/android/platform/packages/providers/MediaProvider/+/637d133d90f49dd18bda5de219184bfa9d6c2deb . The regression was introduced in Android 10 and fixed in Android 11.

**Closed** 2022-04-02 14:58 UTC
Labels: bug

**Comment by GithubContributor832** [comment] 2022-04-02 17:34
Thank you for the response and quick action!
