### ISSUE TITLE
Folder size is shown as 4096

### ISSUE THREAD

**Issue by linsui** [zhanghai/MaterialFiles#283] opened 2020-05-06 08:41 UTC
The size shown in the properties menu of a folder is 4096. I guess this is the size of the folder itself but it would make more sense to show the size of the files in it.
Thanks!

**Comment by zhanghai** [comment] 2020-05-09 22:36
Duplicate of #254 and #204. Please search before opening a new issue.

**Closed by zhanghai** 2020-05-09 22:36 UTC
