### ISSUE TITLE
SFTP: Add support for key passphrase

### ISSUE THREAD

**Issue by IacobIonut01** [zhanghai/MaterialFiles#688] opened 2022-03-07 09:49 UTC
Entering a passphrase protected private keys returns invalid key since there's no EditText box to fill in the passphrase required for the key decryption

**Comment by zhanghai** [comment] 2022-03-07 10:02
Duplicate of #552. You may decrypt your private key for now.

**Closed by zhanghai** 2022-03-07 10:02 UTC
Labels: duplicate, enhancement
