### ISSUE TITLE
[Feature request] Show more metadata

### ISSUE THREAD

**Issue by EmilVogt** [zhanghai/MaterialFiles#231] opened 2020-02-04 21:28 UTC
Is it possible to show more metadata for .jpg, .pdf, .mp4, ...?
Like [exiftool](https://github.com/exiftool/exiftool)

What I found:
[https://github.com/drewnoakes/metadata-extractor](https://github.com/drewnoakes/metadata-extractor)
[https://github.com/adobe/XMP-Toolkit-SDK/](https://github.com/adobe/XMP-Toolkit-SDK/)
[https://github.com/apache/pdfbox](https://github.com/apache/pdfbox)

**Comment by zhanghai** [comment] 2020-02-05 03:10
Duplicate of #47

**Closed by zhanghai** 2020-02-05 03:10 UTC
