### ISSUE TITLE
[bug] Cannot change folder or file name, if only case is changed.

### ISSUE THREAD

**Issue by vishalnandagopal** [zhanghai/MaterialFiles#354] opened 2020-08-11 11:42 UTC
Bug- If a folder/file is named 'example' , I am not able to rename it to 'Example' .

Present solution - Rename to something else and then rename it again to 'Example'.

Thanks!

**Comment by zhanghai** [comment] 2020-08-11 21:26
Duplicate of #312.

**Closed by zhanghai** 2020-08-11 21:26 UTC
