### ISSUE TITLE
FTP server restarted if app is killed after stopping it

### ISSUE THREAD

**Issue by riveravaldez** [zhanghai/MaterialFiles#184] opened 2019-11-25 19:40 UTC
Material Files version: 1.0.0-beta.11 (12)
Android version: 6.0
kernel version: 3.10.49
F-Droid version: 1.7.1
Device: LG-H735AR

**Steps to reproduce:**
1. Open Material Files (Give access to files)
2. Open menu > FTP server
3. Start server
4. Stop server
5. Close application

**Result:**
Server restarts by its own.

That's it.
By the way, the app is beautiful and useful, I really appreciate it and thank your work.

**Comment by zhanghai** [comment] 2019-11-26 09:35
Cannot reproduce on Android 9.0. When you "Close application", do you mean pressing back and get back to home screen?

**Comment by riveravaldez** [comment] 2019-11-26 19:59
> When you "Close application", do you mean pressing back until back to home screen?

I mean pressing the "show open windows/apps" button and removing _Material Files_ window from the screen (so closing the app).

BTW, right now, I can't find _Material Files_ (which I uninstalled yesterday for precaution) in the F-Droid apps-list in my phone neither in the website version[1]. As if it has been removed?

Thanks a lot, best regards.

[1] https://search.f-droid.org/?q=material+files&lang=en

**Comment by zhanghai** [comment] 2019-11-27 00:10
Ah, I can also reproduce it now. This is unexpected, I'll take a look later.

Regarding F-Droid, it's not removed because you can still visit its page at https://f-droid.org/packages/me.zhanghai.android.files . Someone told me that metadata for it is somehow broken but I'm not sure why... https://gitlab.com/fdroid/fdroiddata/issues/1865#note_250484892

**Comment by zhanghai** [comment] 2019-11-27 03:06
Fixed in 8480642 and will be available in 1.0.0.

**Closed by zhanghai** 2019-11-27 03:06 UTC
Labels: bug
