### ISSUE TITLE
[Feature Request] Export & Import settings

### ISSUE THREAD

**Issue by HarriBuh** [zhanghai/MaterialFiles#1182] opened 2024-03-26 17:35 UTC
Please add an option to make backups or at least to manually export (& import) user settings. There are quite some individual things (mainly bookmarks) that are nasty to set up and the possibility to simply import these after resets works be very helpful.

**Comment by zhanghai** [comment] 2024-03-26 18:26
Duplicate of #523.

**Closed by zhanghai** 2024-03-26 18:26 UTC

**Comment by n00b12345** [comment] 2024-07-08 19:47
I use Material Files without root because the app is so good. I therefore do not have access to the data folder. It would really help if you could consider having an export option, if it isn't too much work.
