### ISSUE TITLE
Idea: the ability to save files through the share menu

### ISSUE THREAD

**Issue by blackandyellowgecko** [zhanghai/MaterialFiles#503] opened 2021-04-20 02:27 UTC
Some apps like [Image Saver ](https://play.google.com/store/apps/details?id=com.saver.photoandvideosaver&hl=pt&gl=US) and Solid Explorer (if I'm not mistaken) puts a "save" button in the share menu. Is very useful. For example: if the user disabled the media visibility in WhatsApp, but want to save an image to the Downloads folder, the user needs to go to the WhatsApp folder/WhatsApp Images (or Videos) to get this or turn back on the media visibility option.

**Comment by zhanghai** [comment] 2021-04-20 02:54
Duplicate of #153.

**Closed by zhanghai** 2021-04-20 02:54 UTC
Labels: duplicate, enhancement
