### ISSUE TITLE
[Feature Request] Copy speed indicator with estimated completion time

### ISSUE THREAD

**Issue by VA1DER** [zhanghai/MaterialFiles#776] opened 2022-05-04 16:37 UTC
When performing a large copy or move operation It would be useful to have feedback on how fast files are copying.  Also it would be useful to have an indicator of approximately how long a copy or move operation will take.  This is more especially important now that Material Files supports so many network protocols.

**Comment by zhanghai** [comment] 2022-05-04 21:46
Duplicate of #77.

**Closed by zhanghai** 2022-05-04 21:46 UTC
