### ISSUE TITLE
Feature request, Add support for termux in "open in terminal".

### ISSUE THREAD

**Issue by stevenleeS0ht** [zhanghai/MaterialFiles#301] opened 2020-05-29 07:03 UTC
Currently, "Open in terminal" doesn't support Termux, I am wondering what Intent it calls of this button?

This is a cool feature, If this is a Standard Intent of Terminal App, I am going to have a look if it is possible to let Termux support this.

**Comment by stevenleeS0ht** [comment] 2020-05-31 05:29
@zhanghai , What is your opinion?

**Comment by zhanghai** [comment] 2020-05-31 06:51
Duplicate of #246 and #183.

**Closed by zhanghai** 2020-05-31 06:51 UTC
