### ISSUE TITLE
Unable to read or copy files from SMB Share (on 1.7.0, works fine on 1.6.2)

### ISSUE THREAD

**Issue by Mnky313** [zhanghai/MaterialFiles#1160] opened 2024-03-16 20:55 UTC
Adding an SMB Share works however when trying to open files or copy them to the phone it fails.

Copying files flashes a 0 byte file with the same name which disappears almost immediately

Trying to open files in the image viewer gives a java.lang.NoSuchFieldError:
![Screenshot_20240316_165201_Material Files](https://github.com/zhanghai/MaterialFiles/assets/23646586/fb9f6909-4595-4b86-a79e-7e8d130c0f62)

Uninstalling 1.7.0 and re-installing 1.6.2 fixes the issue.

**Comment by zhanghai** [comment] 2024-03-16 21:01
Thanks for reporting - this is a duplicate of #1154.

**Closed by zhanghai** 2024-03-16 21:01 UTC
