### ISSUE TITLE
GIF speed not properly calculated in preview 

### ISSUE THREAD

**Issue by ThatOneCalculator** [zhanghai/MaterialFiles#977] opened 2023-07-11 21:14 UTC
The speed of each frame is not taken into account when viewing GIFs in a list, leading to very sped-up results. 

Preview:

https://github.com/zhanghai/MaterialFiles/assets/44733677/d11b5c86-ff2f-4727-bfd7-ec9683a3e2be

Original file:

![goblin_shower.gif](https://github.com/zhanghai/MaterialFiles/assets/44733677/24bf85fc-6e70-4983-ba1c-d5cb13bc5b05)

**Comment by zhanghai** [comment] 2023-08-09 02:27
Duplicate of https://github.com/coil-kt/coil/issues/540 and fixed on master with the latest version of Coil. I've verified it's fixed on API 21 and API 33 at least.

**Closed by zhanghai** 2023-08-09 02:27 UTC
Labels: bug
