### ISSUE TITLE
[FEATURE REQUEST/BUG?] Folder Size

### ISSUE THREAD

**Issue by 0xlne** [zhanghai/MaterialFiles#254] opened 2020-03-18 15:01 UTC
It's not possible to display the size of the contents of a folder in properties.
Not sure whether it's a bug or missing feature?
I'm submitting the topic for consideration.

**Comment by zhanghai** [comment] 2020-03-18 20:08
Duplicate of #204

**Closed by zhanghai** 2020-03-18 20:08 UTC
